# Generated by Django 2.0.2 on 2018-03-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
            ],
        ),
    ]
